[package]
name = "cryptarchia-lll-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "cryptarchia-lll"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cryptarchia-lll = { path = "../cryptarchia-lll", features = ["std"] }
